#!/bin/env bash

# Define the script name
SCRIPT_NAME="5-is_the_host_on_the_network"

# Check if an IP address is provided as an argument
if [ $# -eq 0 ]; then
    echo "Usage: $SCRIPT_NAME {IP_ADDRESS}"
    exit 1
fi

# The IP address is taken from the first argument
IP_ADDRESS=$1
ping -c 5 "$IP_ADDRESS"
