#!/bin/env bash
# Check if an IP address is provided as an argument
if [ $# -eq 0 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# The IP address is taken from the first argument
IP_ADDRESS=$1

# Use ping to ping the IP address 5 times
ping -c 5 $IP_ADDRESS
