#!/usr/bin/env bash
# Loops from 1 to 20 and displays:
#   "bad luck from china" for the 4th iteration
#   "bad luck from japan" for the 9th iteration
#   "bad luck from Italy" for the 17th loop iteration
#   numbers for all other iterations

count=1

while [ $count -le 20 ]
do
	echo "$count"
	case $count in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( count++ ))
done
